apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meharpod-rs
  labels:
    app: meharpod
spec:
  replicas: 3
  selector:
    matchLabels:
      laila: majnu
  template:
    metadata:
      labels:
        laila: majnu
    spec:
      containers:
      - name: meharcon
        image: sonambewafaa/hellodhondhu
        ports:
        - containerPort: 80
