apiVersion: v1
kind: Service
metadata:
  name: meharservice
  labels:
    app: meharpod
spec:
  selector:
    laila: majnu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer